import Head from 'next/head'
import withRoot from '../components/modules/withRoot'
import Home2 from './Home'

 function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Home2/>

    </div>
  )
}
export default withRoot(Home)
